name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'   # or 17, 11, depending on your project
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file individualproject/pom.xml

      - name: Run tests
        run: mvn test
